on:
  pull_request:
    branches:
      - main
name: Pa11y tests
jobs:
  wait_for_vercel:
    name: Wait for Vercel preview
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for Vercel preview deployment to be ready
        uses: patrickedqvist/wait-for-vercel-preview@v1.2.0
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 600
  pa11y:
    name: Pa11y tests
    needs: wait_for_vercel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: browser-actions/setup-chrome@latest
      - uses: oven-sh/setup-bun@v2
      - name: Fixup git permissions
        # https://github.com/actions/checkout/issues/766
        shell: bash
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Disable AppArmor User Namespace Restrictions, required to open
          Chrome on Ubuntu 23.10+ without --no-sandbox). See
          https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md.
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
      - run: bun install
      - run: bun run a11y -- ${{ needs.wait_for_vercel.outputs.preview_url }}/sitemap-0.xml
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Build output

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: ./.pa11y/pa11y-results.md
          edit-mode: replace
